[workspace]
resolver = "2"

members = [
    "backends/rust/noble-idl-compiler-rust",
    "backends/rust/noble-idl-rust-plugin",
    "examples/rust",
    "noble-idl-api",
    "noble-idl-compiler",
    "runtime/rust",
]
