[workspace]
resolver = "2"

members = [
    "langs/rust/runtime-derive",
    "langs/rust/runtime",
    "langs/rust/backend",
    "langs/rust/example",
    "noble-idl-api",
    "noble-idl-compiler",
]
