
[versions]
junit-jupiter = "5.10.2"
jvmwasm = "0.1.0"
esexpr = "0.1.0"
apache-commons-text = "1.12.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
esexpr-generator = { module = "dev.argon:esexpr-generator" , version.ref = "esexpr" }
esexpr-runtime = { module = "dev.argon:esexpr-java-runtime" , version.ref = "esexpr" }
jvmwasm-engine = { module = "dev.argon.jvmwasm:wasm-engine", version.ref = "jvmwasm" }
apache-commons-text = { module = "org.apache.commons:commons-text", version.ref = "apache-commons-text" }
